# Generated by Django 5.1.1 on 2024-11-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custome_name', models.CharField(max_length=150)),
                ('region', models.CharField(choices=[('ag', 'Ag'), ('ak', 'Ak'), ('mr', 'Mr'), ('ah', 'Ah'), ('bn', 'Bn'), ('lb', 'Lb'), ('dz', 'Dz')], max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('order_status', models.CharField(choices=[('ordered', 'Ordered'), ('pending', 'Pending'), ('sendend', 'Sendend'), ('delivered', 'Delivered')], default='ordered', max_length=20)),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.cart')),
            ],
        ),
    ]
