# Generated by Django 5.1.1 on 2024-11-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_custome_name_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
